CREATE TABLE IF NOT EXISTS packages (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS commands (
	id INT AUTO_INCREMENT PRIMARY KEY,
	package_id INT,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(255) 
);

CREATE TABLE IF NOT EXISTS options (
	id INT AUTO_INCREMENT PRIMARY KEY,
	command_id INT NOT NULL,
	optional BOOLEAN NOT NULL,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS contents (
	id INT AUTO_INCREMENT PRIMARY KEY,
	command_id INT NOT NULL,
	optional BOOLEAN NOT NULL,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(255)
);